### PR TITLE
Cleanup stream state if there are no subscribers.

### PR DESCRIPTION
**Pull request by johnou**

### CODE REVIEW

**Comment by johnou** [comment]
Failed tests:   testStreamPersistence(cloud.orbit.actors.test.streams.StreamPersistenceTest): expected:<hello3> but was:<null>
  testStreamPersistence(cloud.orbit.actors.test.streams.StreamTest): expected:<hello2> but was:<null>

**Comment by JoeHegarty** [comment]
Do you know why this is failing?

**Comment by johnou** [comment]
Not yet.

**Comment by johnou** [comment]
When shutting down a node the checkAlive fails (because the node will no longer respond to requests) and the subscriber is removed. I think clearing the state without this check is a huge improvement to prevent state storage leaks. We can revisit shutdown another time.

**Comment by johnou** [comment]
leak

**Comment by JoeHegarty** [comment]
Looks good. Thanks Johno

**Pull request merged**
